name: changed-job

on: 
  push: 
  pull_request:

    
jobs:
  meinErsterJob:
    runs-on: ubuntu-latest 

    steps:
      - name: meinErsterStep
        run: echo "Hello World"

      - name: Abschied
        run: echo "Bye bye"
  